worker_process:
  stage: process
  image: ${CI_REGISTRY_IMAGE}/process:latest
  before_script:
    - env | sort
    - date -Iseconds
    - echo "START JOB $CI_JOB_STAGE $CI_JOB_NAME"
    - export VAULT_TOKEN=$(vault write -field=token auth/gitfr_jwt/login role="${VAULT_JWT_ROLE}" jwt="$CI_JOB_JWT")
    - vault token renew -i 30m > /dev/null
  script:
    - python3 ./process/worker.py
  variables:
      SENTRY_DSN: https://XXXXX@sentry.io/44
      VAULT_CREDENTIALS_PATH: secret/data/smartinfra/tools/stoback/morning_check/stoback_tools
  artifacts:
    paths:
      - ./artifacts/output.html
    expire_in: 2 mos
  tags:
    - server-job
  only:
    refs:
      - main
    variables:
      - $CI_PIPELINE_SOURCE == "web"
      - $CI_PIPELINE_SOURCE == "schedule"
