build_lint:
  stage: build
  tags:
    - server-job
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/lint/Dockerfile --destination ${CI_REGISTRY_IMAGE}/lint:latest
  only:
    refs:
      - main
    variables:
      - $CI_PIPELINE_SOURCE == "push"
    changes:
      - lint/Dockerfile